### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by ornicar** [myrrkel/pyzik#5]
```
python pyzik.py 
Available system styles:  ['Windows', 'Fusion']
musicBase
createConnection
loadMusicBase
initMemoryDB
progressClosed=OnClose
1 : /home/thib/music
Traceback (most recent call last):
  File "pyzik.py", line 54, in <module>
    main()
  File "pyzik.py", line 32, in main
    mb.loadMusicBase()
  File "/home/thib/pyzik/musicBase.py", line 39, in loadMusicBase
    self.addGenresDirToAlbums()
  File "/home/thib/pyzik/musicBase.py", line 51, in addGenresDirToAlbums
    if md.styleID >=0:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

commit b4a8a
Python 3.6.5

**Comment by myrrkel** [comment]
Fix in commit b9b03
